siteName: "ChatBot"     # Your ChatBot Name here.
iconPath: "https://images-ext-1.discordapp.net/external/bk15l3IluZ9Yd5CbmXwmzRXNLhntA2kTKM9pPsDeKhg/%3Fsize%3D2048/https/cdn.discordapp.com/icons/1293949144540381185/ddf47008e55e143e7af8d112da80d9c8.webp?format=webp&width=300&height=300"   # Your ICON URL here.
